version: "3"
services:
  pam-cms:
    image: 3dsinteractive/elasticsearch:pam.nano.base.cms:18.0.1
    hostname: pam-cms
    port:
      - 8000:8000
  pam-api:
    image: 3dsinteractive/elasticsearch:pam.nano.base.api:18.0.1
    hostname: pam-api
    ports:
      - 8080:8080
    environment:
      - DEBUG=true
      - SEAMAN_TIMEZONE_NAME=UTC+0
      - SEAMAN_TIMEZONE_OFFSET=0
      - SEAMAN_MONITORING=false
      - SEAMAN_PORT=8080
      - PAM4_ELS_VERSION=6.8
      - PAM4_SECRET=
      - PAM4_ADMINEMAIL_SENDER=admin@3dsinteractive.com
      - PAM4_ADMINEMAIL_SENDERNAME=PAM Admin
      - PAM4_TIMEOFDAY_OFFSET=7
      - PAM4_TIMEOFDAY_LOCATIONNAME=UTC+7
      - PAM4_E2E_URL=http://localhost:8080
      - PAM4_DATADIR=/app/data
      - PAM4_INDEXER_ENDPOINTS=http://elasticsearch:9200
      - PAM4_INDEXER_SNIFF=false
      - PAM4_INDEXER_GZIP=true
      - PAM4_CMS_API_ENDPOINT=http://pam-cms:8000/api
      - PAM4_CMS_API_APPID=
      - PAM4_CMS_API_SECRET=
      - PAM4_CMS_API_TIMEOUT=3
      - PAM4_CONNECT_API_ENDPOINT=http://pam-api:8080
      - PAM4_CONNECT_API_APPID=
      - PAM4_CONNECT_API_SECRET=
      - PAM4_CONNECT_API_TIMEOUT=3
      - PAM4_AI_API_APPID=
      - PAM4_AI_API_SECRET=
      - PAM4_AI_API_TIMEOUT=3
      - PAM4_CACHER_ENDPOINT=redis:6379
      - PAM4_CACHER_PASSWORD=
      - PAM4_CACHER_DB=0
      - PAM4_CONSUMER_ENDPOINT=kafka:9092
      - PAM4_PRODUCER_ENDPOINT=kafka:9092
      - PAM4_ALLOW_DOMAINS=*
      - PAM4_ALLOW_HEADERS=Origin,DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,csrf,Set-Cookie,x-secret
      - PAM4_TRACKERRECEIVEDCONSUME_BATCHSIZE=50
      - PAM4_TRACKERRECEIVEDCONSUME_BATCHTIMEOUT=100
      - PAM4_EVALTRIGGERCONSUME_BATCHSIZE=50
      - PAM4_EVALTRIGGERCONSUME_TIMEOUT=100
      - PAM4_EVALTRIGGERCOMMANDS_BATCHSIZE=50
      - PAM4_EVALTRIGGERCOMMANDS_TIMEOUT=100
      - PAM4_EVALTRACKERCONSUME_BATCHSIZE=50
      - PAM4_EVALTRACKERCONSUME_TIMEOUT=100
      - PAM4_EVALTRACKERCOMMANDS_BATCHSIZE=50
      - PAM4_EVALTRACKERCOMMANDS_TIMEOUT=100
      - PAM4_EVALTRACKER_DATAPERIOD=180
      - PAM4_CONTACTIMPORTCONSUME_BATCHSIZE=50
      - PAM4_CONTACTIMPORTCONSUME_TIMEOUT=100
      - PAM4_CONTACTIMPORTCOMMANDS_BATCHSIZE=50
      - PAM4_CONTACTIMPORTCOMMANDS_TIMEOUT=100
      - PAM4_MERGEDCONTACTCONSUME_BATCHSIZE=50
      - PAM4_MERGEDCONTACTCONSUME_TIMEOUT=100
      - PAM4_MERGEDCONTACTCOMMANDS_BATCHSIZE=50
      - PAM4_MERGEDCONTACTCOMMANDS_TIMEOUT=100
      - PAM4_DEFAULT_PAGELIMIT=50
      - PAM4_MAX_PAGELIMIT=500
      - PAM4_PRODUCT_TRENDS_LIMIT=100
      - PAM4_CACHE_EXPIRE_TIME_CONTACTATTRS=120
      - PAM4_CACHE_EXPIRE_TIME_TRIGGERATTRS=120
      - PAM4_CACHE_EXPIRE_TIME_AIATTRS=120
      - PAM4_CACHE_EXPIRE_TIME_MEDIAATTRS=120
      - PAM4_CACHE_EXPIRE_TIME_PRODUCTATTRS=120
      - PAM4_CACHE_EXPIRE_TIME_TRACKERATTRS=120
      - PAM4_CACHE_EXPIRE_TIME_CAMPAIGNATTRS=120
      - PAM4_CACHE_EXPIRE_TIME_PRODUCT_TRENDS=120
      - PAM4_CACHE_EXPIRE_TIME_REPORT=120
      - PAM4_CACHE_EXPIRE_TIME_AUDIENCEATTRS=120
      - PAM4_INDEXERWORKER_POOLSIZE=50
      - PAM4_DOCKER_USERNAME=
      - PAM4_DOCKER_PASSWORD=
      - PAM4_DOCKER_NETWORK=
      - PAM4_SCHEDULE_APPPUSHNOTI=60
      - PAM4_SCHEDULE_SPDAYS_TRIGGERS=3600
      - PAM4_SCHEDULE_CAMPAIGNNOTENGAGE_TRIGGERS=1800
      - PAM4_SCHEDULE_PRODUCTS_TRENDS=3600
      - PAM4_SCHEDULE_CONTACT_EXPORT_FILE_DELETE=3600
      - PAM4_FILE_AGE_IN_DAYS=7
      - PAM4_MAILER_SERVER=127.0.0.1
      - PAM4_MAILER_PORT=1025
      - PAM4_MAILER_USER=admin
      - PAM4_MAILER_PASSWORD=admin
      - PAM4_FILESTORE_ENDPOINT=127.0.0.1:9001
      - PAM4_FILESTORE_ACCESSKEY=mno_access_key
      - PAM4_FILESTORE_SECRET=mno_secret_key
      - PAM4_FILESTORE_ISHTTPS=false
      - PAM4_FILESTORE_BUCKETNAME=public-test
      - PAM4_FILESTORE_TIMEOUT=5
      - PAM4_MQ_PARTITIONS=1
      - PAM4_MQ_REPLICATIONS=1
      - PAM4_DOCKER_LOGGING_DRIVER=
      - PAM4_DOCKER_LOGGING_FLUENTD_ENDPOINT=
      - PAM4_DOCKER_VOLUMES_WORKERS=
      - PAM4_DOCKER_VOLUMES_SENDERS=
      - PAM4_CMS_FRONTEND_URL=http://pam-cms:8081
      - ECOM_AUTHENTICATION=true
      - ENABLE_UPDATE_CONNECT_USER=false
      - PAM_TRACKER_EVENT_INDEXD_NAMES='{"trackers_update_attribute":"update_attribute","trackers_allow_consent":"allow_consent","trackers_page_view":"page_view,pageview","trackers_pam_story":"pam_story","trackers_pam_metric":"pam_metric","trackers_chat":"chat","trackers":""}'
      - PAM_TRACKER_EVENT_SET_LINKED_CONTACT_SYNONYMS="allow_consent,set_linked_contact"
      - PAM_TRACKER_EVENT_FIND_LINKED_CONTACT_SYNONYMS="allow_consent,login,page_viewed,member_registered"
      - PAM_TRACKER_EVENT_NON_INDEX_FORM_FIELD_INDEXD_NAMES="trackers_update_attribute"
      - PAM_TRACKER_EVENT_EVAL_SEGMENT_INDEXD_NAMES="trackers_page_view,trackers_chat,trackers"
      - PAM_HAS_MIGRATE_CONTACT_DELIVERS_APP_PUSH=true
      - PAM_EXIT_WHEN_MIGRATE_FINISH=true
      - PAM_ENABLE_MIGRATE_ECOM=false
      - PAM_EVALUATE_CONTACT_TRIGGERS_PARTITIONS=10
  elasticsearch:
    image: 3dsinteractive/elasticsearch:6.8-custom
    hostname: elasticsearch
    environment:
      - ELASTICSEARCH_CLUSTER_NAME=elasticsearch
      - ELASTICSEARCH_CLUSTER_HOSTS=elasticsearch
      - ELASTICSEARCH_NODE_NAME=elasticsearch
      - ELASTICSEARCH_NODE_TYPE=master
      - ELASTICSEARCH_PORT_NUMBER=9200
      - ELASTICSEARCH_HEAP_SIZE=1g
      - ELASTICSEARCH_CUSTOM_MAX_CLAUSE_COUNT=10000
      - ELASTICSEARCH_CUSTOM_QUERY_CACHE_SIZE=30%
      - ELASTICSEARCH_CUSTOM_MEMORY_LOCK=true
      - ELASTICSEARCH_CUSTOM_BULK_QUEUE_SIZE=50
      - ELASTICSEARCH_CUSTOM_INDEX_QUEUE_SIZE=100
      - ELASTICSEARCH_PLUGINS=analysis-icu
    ports:
      - 9200:9200
    volumes:
      - ./dockers/elasticsearch/data:/bitnami/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
  kibana:
    image: 3dsinteractive/kibana:6.8
    links: 
      - elasticsearch
    ports:
      - 5601:5601
  zookeeper:
    image: 3dsinteractive/zookeeper:3.0
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 3dsinteractive/kafka:2.0-custom
    ports:
      - 9094:9094
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://:9092,OUTSIDE://127.0.0.1:9094
      - KAFKA_LISTENERS=INSIDE://:9092,OUTSIDE://:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
      - KAFKA_HEAP_OPTS=-Xmx1500m -Xms1500m
    volumes:
      - ./dockers/kafka/config:/opt/bitnami/kafka/conf
      - ./dockers/kafka/data:/bitnami/kafka/data
  redis:
    image: 3dsinteractive/redis:4.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
networks:
  default:
    external:
      name: network-default
